title: Sebastian Marrero
baseurl: "/Portfolio-Site"
url: "https://sebastianmarrero.github.io"

remote_theme: jamigibbs/phantom

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM

email: 'sebastianmarrero64@gmail.com'
description: "I’m passionate about analytics and uncovering meaningful insights from data. I enjoy using Python and SQL. Check out my projects and other interests below!"
author:
  name: Sebastian Marrero
  avatar: "/Portfolio-Site/assets/images/profile.jpg"
  bio: Economics + Data Science | Instinet | Vanderbilt

github_username: 'SebastianMarrero'
linkedin_url: "https://www.linkedin.com/in/sebastianmarrero/"
kaggle_url: "https://www.kaggle.com/sebastianmarrero64"
tableau_url: "https://public.tableau.com/app/profile/sebastian.marrero/vizzes"

# Pagination config
paginate: 10
paginate_path: "/page:num/"

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

# Phantom theme settings
footer_text: '© 2025 Sebastian Marrero'
admin_name: 'Sebastian Marrero'
google_analytics: "UA-9999999-99"
enable_contact: false

enable_nav: true
nav_item:
  - { url: '{{ site.baseurl }}/', text: 'Home' }
  - { url: '{{ site.baseurl }}/about/', text: 'About' }
  - { url: '{{ site.baseurl }}/projects/', text: 'Projects' }
  - { url: '{{ site.baseurl }}/resume/', text: 'Resume' }
  - { url: '{{ site.baseurl }}/contact/', text: 'Contact' }

